[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
unsecure_program = "XecCxw3qsZmnD9xKh9D718hvw4P9TfwMEKG9Fh54oFd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
